"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2025 The Dapr Authors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from dapr.proto.common.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetConfigurationRequest(_message.Message):
    """GetConfigurationRequest is the message to get a list of key-value configuration from specified configuration store."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STORE_NAME_FIELD_NUMBER: _builtins.int
    KEYS_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    store_name: _builtins.str
    """Required. The name of configuration store."""
    @_builtins.property
    def keys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Optional. The key of the configuration item to fetch.
        If set, only query for the specified configuration items.
        Empty list means fetch all.
        """

    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Optional. The metadata which will be sent to configuration store components."""

    def __init__(
        self,
        *,
        store_name: _builtins.str = ...,
        keys: _abc.Iterable[_builtins.str] | None = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["keys", b"keys", "metadata", b"metadata", "store_name", b"store_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetConfigurationRequest: _TypeAlias = GetConfigurationRequest  # noqa: Y015

@_typing.final
class GetConfigurationResponse(_message.Message):
    """GetConfigurationResponse is the response conveying the list of configuration values.
    It should be the FULL configuration of specified application which contains all of its configuration items.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ItemsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _common_pb2.ConfigurationItem: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _common_pb2.ConfigurationItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.MessageMap[_builtins.str, _common_pb2.ConfigurationItem]: ...
    def __init__(
        self,
        *,
        items: _abc.Mapping[_builtins.str, _common_pb2.ConfigurationItem] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetConfigurationResponse: _TypeAlias = GetConfigurationResponse  # noqa: Y015

@_typing.final
class SubscribeConfigurationRequest(_message.Message):
    """SubscribeConfigurationRequest is the message to get a list of key-value configuration from specified configuration store."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STORE_NAME_FIELD_NUMBER: _builtins.int
    KEYS_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    store_name: _builtins.str
    """The name of configuration store."""
    @_builtins.property
    def keys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Optional. The key of the configuration item to fetch.
        If set, only query for the specified configuration items.
        Empty list means fetch all.
        """

    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """The metadata which will be sent to configuration store components."""

    def __init__(
        self,
        *,
        store_name: _builtins.str = ...,
        keys: _abc.Iterable[_builtins.str] | None = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["keys", b"keys", "metadata", b"metadata", "store_name", b"store_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeConfigurationRequest: _TypeAlias = SubscribeConfigurationRequest  # noqa: Y015

@_typing.final
class UnsubscribeConfigurationRequest(_message.Message):
    """UnSubscribeConfigurationRequest is the message to stop watching the key-value configuration."""

    DESCRIPTOR: _descriptor.Descriptor

    STORE_NAME_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    store_name: _builtins.str
    """The name of configuration store."""
    id: _builtins.str
    """The id to unsubscribe."""
    def __init__(
        self,
        *,
        store_name: _builtins.str = ...,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "store_name", b"store_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnsubscribeConfigurationRequest: _TypeAlias = UnsubscribeConfigurationRequest  # noqa: Y015

@_typing.final
class SubscribeConfigurationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ItemsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _common_pb2.ConfigurationItem: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _common_pb2.ConfigurationItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Subscribe id, used to stop subscription."""
    @_builtins.property
    def items(self) -> _containers.MessageMap[_builtins.str, _common_pb2.ConfigurationItem]:
        """The list of items containing configuration values"""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        items: _abc.Mapping[_builtins.str, _common_pb2.ConfigurationItem] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeConfigurationResponse: _TypeAlias = SubscribeConfigurationResponse  # noqa: Y015

@_typing.final
class UnsubscribeConfigurationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OK_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    ok: _builtins.bool
    message: _builtins.str
    def __init__(
        self,
        *,
        ok: _builtins.bool = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnsubscribeConfigurationResponse: _TypeAlias = UnsubscribeConfigurationResponse  # noqa: Y015
