coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%

ignore:
  - dapr/proto # - Generated GRPC client
  - tests      # - tests
  - .tox       # - environment
