[tool.ruff]
target-version = "py310"
line-length = 100
fix = true
extend-exclude = [".github", "dapr/proto"]

[tool.ruff.lint]
select = [
  "I",  # isort
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "E",  # pycodestyle errors

  # TODO: Add those back progressively as we fix the issues
  # "C",  # flake8-comprehensions
  # "B",  # flake8-bugbear
  # "UP",  # pyupgrade
]

# TODO: Add those back progressively as we fix the issues
ignore = ["E501","E203", "E712", "E722", "E713"]

[tool.ruff.format]
quote-style = 'single'
