apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configurationstore
  namespace: default
spec:
  type: configuration.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""