"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) Microsoft Corporation.
Licensed under the MIT License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
from dapr.ext.workflow._durabletask.internal import history_events_pb2 as _history_events_pb2
from dapr.ext.workflow._durabletask.internal import orchestration_pb2 as _orchestration_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AddEventRequest(_message.Message):
    """Request payload for adding new workflow events."""

    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_FIELD_NUMBER: _builtins.int
    EVENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def instance(self) -> _orchestration_pb2.WorkflowInstance:
        """The ID of the workflow to send an event to."""

    @_builtins.property
    def event(self) -> _history_events_pb2.HistoryEvent:
        """The event to send to the workflow."""

    def __init__(
        self,
        *,
        instance: _orchestration_pb2.WorkflowInstance | None = ...,
        event: _history_events_pb2.HistoryEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "instance", b"instance"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "instance", b"instance"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AddEventRequest: _TypeAlias = AddEventRequest  # noqa: Y015

@_typing.final
class AddEventResponse(_message.Message):
    """Response payload for adding new workflow events.
    No fields
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___AddEventResponse: _TypeAlias = AddEventResponse  # noqa: Y015

@_typing.final
class CompleteActivityWorkItemRequest(_message.Message):
    """Request payload for completing an activity work item."""

    DESCRIPTOR: _descriptor.Descriptor

    COMPLETIONTOKEN_FIELD_NUMBER: _builtins.int
    RESPONSEEVENT_FIELD_NUMBER: _builtins.int
    completionToken: _builtins.str
    """The completion token that was provided when the work item was fetched."""
    @_builtins.property
    def responseEvent(self) -> _history_events_pb2.HistoryEvent:
        """The response event that will be sent to the workflow.
        This must be either a TaskCompleted event or a TaskFailed event.
        """

    def __init__(
        self,
        *,
        completionToken: _builtins.str = ...,
        responseEvent: _history_events_pb2.HistoryEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["responseEvent", b"responseEvent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completionToken", b"completionToken", "responseEvent", b"responseEvent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompleteActivityWorkItemRequest: _TypeAlias = CompleteActivityWorkItemRequest  # noqa: Y015

@_typing.final
class CompleteActivityWorkItemResponse(_message.Message):
    """Response payload for completing an activity work item.
    No fields
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CompleteActivityWorkItemResponse: _TypeAlias = CompleteActivityWorkItemResponse  # noqa: Y015

@_typing.final
class CompleteWorkflowWorkItemRequest(_message.Message):
    """Request payload for completing a workflow work item."""

    DESCRIPTOR: _descriptor.Descriptor

    COMPLETIONTOKEN_FIELD_NUMBER: _builtins.int
    INSTANCE_FIELD_NUMBER: _builtins.int
    RUNTIMESTATUS_FIELD_NUMBER: _builtins.int
    CUSTOMSTATUS_FIELD_NUMBER: _builtins.int
    NEWHISTORY_FIELD_NUMBER: _builtins.int
    NEWTASKS_FIELD_NUMBER: _builtins.int
    NEWTIMERS_FIELD_NUMBER: _builtins.int
    NEWMESSAGES_FIELD_NUMBER: _builtins.int
    NUMEVENTSPROCESSED_FIELD_NUMBER: _builtins.int
    completionToken: _builtins.str
    """The completion token that was provided when the work item was fetched."""
    runtimeStatus: _orchestration_pb2.OrchestrationStatus.ValueType
    @_builtins.property
    def instance(self) -> _orchestration_pb2.WorkflowInstance: ...
    @_builtins.property
    def customStatus(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def newHistory(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def newTasks(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def newTimers(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def newMessages(self) -> _containers.RepeatedCompositeFieldContainer[Global___WorkflowMessage]: ...
    @_builtins.property
    def numEventsProcessed(self) -> _wrappers_pb2.Int32Value:
        """The number of work item events that were processed by the workflow.
        This field is optional. If not set, the service should assume that the workflow processed all events.
        """

    def __init__(
        self,
        *,
        completionToken: _builtins.str = ...,
        instance: _orchestration_pb2.WorkflowInstance | None = ...,
        runtimeStatus: _orchestration_pb2.OrchestrationStatus.ValueType = ...,
        customStatus: _wrappers_pb2.StringValue | None = ...,
        newHistory: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        newTasks: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        newTimers: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        newMessages: _abc.Iterable[Global___WorkflowMessage] | None = ...,
        numEventsProcessed: _wrappers_pb2.Int32Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["customStatus", b"customStatus", "instance", b"instance", "numEventsProcessed", b"numEventsProcessed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completionToken", b"completionToken", "customStatus", b"customStatus", "instance", b"instance", "newHistory", b"newHistory", "newMessages", b"newMessages", "newTasks", b"newTasks", "newTimers", b"newTimers", "numEventsProcessed", b"numEventsProcessed", "runtimeStatus", b"runtimeStatus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompleteWorkflowWorkItemRequest: _TypeAlias = CompleteWorkflowWorkItemRequest  # noqa: Y015

@_typing.final
class CompleteWorkflowWorkItemResponse(_message.Message):
    """Response payload for completing a workflow work item.
    No fields
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CompleteWorkflowWorkItemResponse: _TypeAlias = CompleteWorkflowWorkItemResponse  # noqa: Y015

@_typing.final
class WorkflowMessage(_message.Message):
    """A message to be delivered to a workflow by the backend."""

    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_FIELD_NUMBER: _builtins.int
    EVENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def instance(self) -> _orchestration_pb2.WorkflowInstance:
        """The ID of the workflow instance to receive the message."""

    @_builtins.property
    def event(self) -> _history_events_pb2.HistoryEvent:
        """The event payload to be received by the target workflow."""

    def __init__(
        self,
        *,
        instance: _orchestration_pb2.WorkflowInstance | None = ...,
        event: _history_events_pb2.HistoryEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "instance", b"instance"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "instance", b"instance"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WorkflowMessage: _TypeAlias = WorkflowMessage  # noqa: Y015

@_typing.final
class BackendWorkflowState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INBOX_FIELD_NUMBER: _builtins.int
    HISTORY_FIELD_NUMBER: _builtins.int
    CUSTOMSTATUS_FIELD_NUMBER: _builtins.int
    GENERATION_FIELD_NUMBER: _builtins.int
    generation: _builtins.int
    @_builtins.property
    def inbox(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def history(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def customStatus(self) -> _wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        inbox: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        history: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        customStatus: _wrappers_pb2.StringValue | None = ...,
        generation: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["customStatus", b"customStatus"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["customStatus", b"customStatus", "generation", b"generation", "history", b"history", "inbox", b"inbox"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BackendWorkflowState: _TypeAlias = BackendWorkflowState  # noqa: Y015

@_typing.final
class CreateWorkflowInstanceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STARTEVENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def startEvent(self) -> _history_events_pb2.HistoryEvent: ...
    def __init__(
        self,
        *,
        startEvent: _history_events_pb2.HistoryEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["startEvent", b"startEvent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["startEvent", b"startEvent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateWorkflowInstanceRequest: _TypeAlias = CreateWorkflowInstanceRequest  # noqa: Y015

@_typing.final
class WorkflowMetadata(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSTANCEID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    RUNTIMESTATUS_FIELD_NUMBER: _builtins.int
    CREATEDAT_FIELD_NUMBER: _builtins.int
    LASTUPDATEDAT_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    CUSTOMSTATUS_FIELD_NUMBER: _builtins.int
    FAILUREDETAILS_FIELD_NUMBER: _builtins.int
    COMPLETEDAT_FIELD_NUMBER: _builtins.int
    PARENTINSTANCEID_FIELD_NUMBER: _builtins.int
    instanceId: _builtins.str
    name: _builtins.str
    runtimeStatus: _orchestration_pb2.OrchestrationStatus.ValueType
    parentInstanceId: _builtins.str
    @_builtins.property
    def createdAt(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastUpdatedAt(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def input(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def output(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def customStatus(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def failureDetails(self) -> _orchestration_pb2.TaskFailureDetails: ...
    @_builtins.property
    def completedAt(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        instanceId: _builtins.str = ...,
        name: _builtins.str = ...,
        runtimeStatus: _orchestration_pb2.OrchestrationStatus.ValueType = ...,
        createdAt: _timestamp_pb2.Timestamp | None = ...,
        lastUpdatedAt: _timestamp_pb2.Timestamp | None = ...,
        input: _wrappers_pb2.StringValue | None = ...,
        output: _wrappers_pb2.StringValue | None = ...,
        customStatus: _wrappers_pb2.StringValue | None = ...,
        failureDetails: _orchestration_pb2.TaskFailureDetails | None = ...,
        completedAt: _timestamp_pb2.Timestamp | None = ...,
        parentInstanceId: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["completedAt", b"completedAt", "createdAt", b"createdAt", "customStatus", b"customStatus", "failureDetails", b"failureDetails", "input", b"input", "lastUpdatedAt", b"lastUpdatedAt", "output", b"output"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completedAt", b"completedAt", "createdAt", b"createdAt", "customStatus", b"customStatus", "failureDetails", b"failureDetails", "input", b"input", "instanceId", b"instanceId", "lastUpdatedAt", b"lastUpdatedAt", "name", b"name", "output", b"output", "parentInstanceId", b"parentInstanceId", "runtimeStatus", b"runtimeStatus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WorkflowMetadata: _TypeAlias = WorkflowMetadata  # noqa: Y015

@_typing.final
class BackendWorkflowStateMetadata(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INBOXLENGTH_FIELD_NUMBER: _builtins.int
    HISTORYLENGTH_FIELD_NUMBER: _builtins.int
    GENERATION_FIELD_NUMBER: _builtins.int
    SIGNATURELENGTH_FIELD_NUMBER: _builtins.int
    SIGNINGCERTIFICATELENGTH_FIELD_NUMBER: _builtins.int
    inboxLength: _builtins.int
    historyLength: _builtins.int
    generation: _builtins.int
    signatureLength: _builtins.int
    """Number of HistorySignature entries stored (signature-NNNNNN keys)."""
    signingCertificateLength: _builtins.int
    """Number of SigningCertificate entries stored (sigcert-NNNNNN keys)."""
    def __init__(
        self,
        *,
        inboxLength: _builtins.int = ...,
        historyLength: _builtins.int = ...,
        generation: _builtins.int = ...,
        signatureLength: _builtins.int = ...,
        signingCertificateLength: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["generation", b"generation", "historyLength", b"historyLength", "inboxLength", b"inboxLength", "signatureLength", b"signatureLength", "signingCertificateLength", b"signingCertificateLength"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BackendWorkflowStateMetadata: _TypeAlias = BackendWorkflowStateMetadata  # noqa: Y015

@_typing.final
class SigningCertificate(_message.Message):
    """A signing identity's X.509 certificate, stored once and referenced by index
    from HistorySignature entries. This avoids duplicating the certificate
    across every signature from the same identity. Stored as individual actor
    state keys: sigcert-000000, sigcert-000001, etc.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CERTIFICATE_FIELD_NUMBER: _builtins.int
    certificate: _builtins.bytes
    """X.509 certificate chain of the signing identity. Certificates are
    DER-encoded and concatenated directly in order: leaf first, followed by
    intermediates. Each certificate is a self-delimiting ASN.1 SEQUENCE,
    so the chain can be parsed by reading consecutive DER structures.
    """
    def __init__(
        self,
        *,
        certificate: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["certificate", b"certificate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SigningCertificate: _TypeAlias = SigningCertificate  # noqa: Y015

@_typing.final
class HistorySignature(_message.Message):
    """Signing metadata for a contiguous range of history events.
    This is metadata-only — it does NOT contain the events themselves.
    Events are stored once in history-NNNNNN keys; this message references them
    by index range and stores only the signing artifacts.
    Stored as individual actor state keys: signature-000000, signature-000001,
    etc.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STARTEVENTINDEX_FIELD_NUMBER: _builtins.int
    EVENTCOUNT_FIELD_NUMBER: _builtins.int
    PREVIOUSSIGNATUREDIGEST_FIELD_NUMBER: _builtins.int
    EVENTSDIGEST_FIELD_NUMBER: _builtins.int
    CERTIFICATEINDEX_FIELD_NUMBER: _builtins.int
    SIGNATURE_FIELD_NUMBER: _builtins.int
    startEventIndex: _builtins.int
    """Index of the first event covered by this signature (inclusive)."""
    eventCount: _builtins.int
    """Number of events covered by this signature."""
    previousSignatureDigest: _builtins.bytes
    """SHA-256 digest of the previous HistorySignature message (the entire
    deterministically serialized protobuf message). Absent for the first
    signature in the chain (no predecessor). When computing the signature
    input for the root case, this value is treated as empty (zero-length).
    """
    eventsDigest: _builtins.bytes
    """SHA-256 digest over the concatenation of the raw serialized bytes of each
    history event in this range, in order. The bytes are the exact values
    persisted to the state store (one per history-NNNNNN key).
    """
    certificateIndex: _builtins.int
    """Index into the SigningCertificate table (sigcert-NNNNNN keys).
    Multiple signatures from the same identity share the same index.
    A new entry is appended only when the certificate rotates.
    """
    signature: _builtins.bytes
    """Cryptographic signature over
    SHA-256(previousSignatureDigest || eventsDigest)
    using the private key corresponding to the referenced certificate.
    The algorithm is determined by the certificate's key type:
      Ed25519: raw Ed25519 signature over the input bytes
      ECDSA:   fixed-size r||s over SHA-256(input), each component
               zero-padded to the curve byte length
      RSA:     PKCS#1 v1.5 with SHA-256
    """
    def __init__(
        self,
        *,
        startEventIndex: _builtins.int = ...,
        eventCount: _builtins.int = ...,
        previousSignatureDigest: _builtins.bytes | None = ...,
        eventsDigest: _builtins.bytes = ...,
        certificateIndex: _builtins.int = ...,
        signature: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_previousSignatureDigest", b"_previousSignatureDigest", "previousSignatureDigest", b"previousSignatureDigest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_previousSignatureDigest", b"_previousSignatureDigest", "certificateIndex", b"certificateIndex", "eventCount", b"eventCount", "eventsDigest", b"eventsDigest", "previousSignatureDigest", b"previousSignatureDigest", "signature", b"signature", "startEventIndex", b"startEventIndex"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__previousSignatureDigest: _TypeAlias = _typing.Literal["previousSignatureDigest"]  # noqa: Y015
    _WhichOneofArgType__previousSignatureDigest: _TypeAlias = _typing.Literal["_previousSignatureDigest", b"_previousSignatureDigest"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__previousSignatureDigest) -> _WhichOneofReturnType__previousSignatureDigest | None: ...

Global___HistorySignature: _TypeAlias = HistorySignature  # noqa: Y015

@_typing.final
class DurableTimer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMEREVENT_FIELD_NUMBER: _builtins.int
    GENERATION_FIELD_NUMBER: _builtins.int
    generation: _builtins.int
    @_builtins.property
    def timerEvent(self) -> _history_events_pb2.HistoryEvent: ...
    def __init__(
        self,
        *,
        timerEvent: _history_events_pb2.HistoryEvent | None = ...,
        generation: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timerEvent", b"timerEvent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["generation", b"generation", "timerEvent", b"timerEvent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DurableTimer: _TypeAlias = DurableTimer  # noqa: Y015
