"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2025 The Dapr Authors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
from dapr.ext.workflow._durabletask.internal import history_events_pb2 as _history_events_pb2
from dapr.ext.workflow._durabletask.internal import orchestration_pb2 as _orchestration_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RuntimeStateStalled(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REASON_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    reason: _orchestration_pb2.StalledReason.ValueType
    description: _builtins.str
    def __init__(
        self,
        *,
        reason: _orchestration_pb2.StalledReason.ValueType = ...,
        description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...

Global___RuntimeStateStalled: _TypeAlias = RuntimeStateStalled  # noqa: Y015

@_typing.final
class WorkflowRuntimeState(_message.Message):
    """WorkflowRuntimeState holds the current state for a workflow."""

    DESCRIPTOR: _descriptor.Descriptor

    INSTANCEID_FIELD_NUMBER: _builtins.int
    NEWEVENTS_FIELD_NUMBER: _builtins.int
    OLDEVENTS_FIELD_NUMBER: _builtins.int
    PENDINGTASKS_FIELD_NUMBER: _builtins.int
    PENDINGTIMERS_FIELD_NUMBER: _builtins.int
    PENDINGMESSAGES_FIELD_NUMBER: _builtins.int
    STARTEVENT_FIELD_NUMBER: _builtins.int
    COMPLETEDEVENT_FIELD_NUMBER: _builtins.int
    CREATEDTIME_FIELD_NUMBER: _builtins.int
    LASTUPDATEDTIME_FIELD_NUMBER: _builtins.int
    COMPLETEDTIME_FIELD_NUMBER: _builtins.int
    CONTINUEDASNEW_FIELD_NUMBER: _builtins.int
    ISSUSPENDED_FIELD_NUMBER: _builtins.int
    CUSTOMSTATUS_FIELD_NUMBER: _builtins.int
    STALLED_FIELD_NUMBER: _builtins.int
    instanceId: _builtins.str
    continuedAsNew: _builtins.bool
    isSuspended: _builtins.bool
    @_builtins.property
    def newEvents(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def oldEvents(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def pendingTasks(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def pendingTimers(self) -> _containers.RepeatedCompositeFieldContainer[_history_events_pb2.HistoryEvent]: ...
    @_builtins.property
    def pendingMessages(self) -> _containers.RepeatedCompositeFieldContainer[Global___WorkflowRuntimeStateMessage]: ...
    @_builtins.property
    def startEvent(self) -> _history_events_pb2.ExecutionStartedEvent: ...
    @_builtins.property
    def completedEvent(self) -> _history_events_pb2.ExecutionCompletedEvent: ...
    @_builtins.property
    def createdTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastUpdatedTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def completedTime(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def customStatus(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def stalled(self) -> Global___RuntimeStateStalled: ...
    def __init__(
        self,
        *,
        instanceId: _builtins.str = ...,
        newEvents: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        oldEvents: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        pendingTasks: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        pendingTimers: _abc.Iterable[_history_events_pb2.HistoryEvent] | None = ...,
        pendingMessages: _abc.Iterable[Global___WorkflowRuntimeStateMessage] | None = ...,
        startEvent: _history_events_pb2.ExecutionStartedEvent | None = ...,
        completedEvent: _history_events_pb2.ExecutionCompletedEvent | None = ...,
        createdTime: _timestamp_pb2.Timestamp | None = ...,
        lastUpdatedTime: _timestamp_pb2.Timestamp | None = ...,
        completedTime: _timestamp_pb2.Timestamp | None = ...,
        continuedAsNew: _builtins.bool = ...,
        isSuspended: _builtins.bool = ...,
        customStatus: _wrappers_pb2.StringValue | None = ...,
        stalled: Global___RuntimeStateStalled | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_stalled", b"_stalled", "completedEvent", b"completedEvent", "completedTime", b"completedTime", "createdTime", b"createdTime", "customStatus", b"customStatus", "lastUpdatedTime", b"lastUpdatedTime", "stalled", b"stalled", "startEvent", b"startEvent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_stalled", b"_stalled", "completedEvent", b"completedEvent", "completedTime", b"completedTime", "continuedAsNew", b"continuedAsNew", "createdTime", b"createdTime", "customStatus", b"customStatus", "instanceId", b"instanceId", "isSuspended", b"isSuspended", "lastUpdatedTime", b"lastUpdatedTime", "newEvents", b"newEvents", "oldEvents", b"oldEvents", "pendingMessages", b"pendingMessages", "pendingTasks", b"pendingTasks", "pendingTimers", b"pendingTimers", "stalled", b"stalled", "startEvent", b"startEvent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__stalled: _TypeAlias = _typing.Literal["stalled"]  # noqa: Y015
    _WhichOneofArgType__stalled: _TypeAlias = _typing.Literal["_stalled", b"_stalled"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__stalled) -> _WhichOneofReturnType__stalled | None: ...

Global___WorkflowRuntimeState: _TypeAlias = WorkflowRuntimeState  # noqa: Y015

@_typing.final
class WorkflowRuntimeStateMessage(_message.Message):
    """WorkflowRuntimeStateMessage holds a HistoryEvent payload and the target instance ID."""

    DESCRIPTOR: _descriptor.Descriptor

    HISTORYEVENT_FIELD_NUMBER: _builtins.int
    TARGETINSTANCEID_FIELD_NUMBER: _builtins.int
    PROPAGATEDHISTORY_FIELD_NUMBER: _builtins.int
    targetInstanceId: _builtins.str
    @_builtins.property
    def historyEvent(self) -> _history_events_pb2.HistoryEvent: ...
    @_builtins.property
    def propagatedHistory(self) -> _history_events_pb2.PropagatedHistory:
        """Propagated history to deliver to the child workflow.
        This is a transport field used when creating child workflows with
        history propagation enabled. It is NOT stored as part of any
        workflow's history events.
        """

    def __init__(
        self,
        *,
        historyEvent: _history_events_pb2.HistoryEvent | None = ...,
        targetInstanceId: _builtins.str = ...,
        propagatedHistory: _history_events_pb2.PropagatedHistory | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_propagatedHistory", b"_propagatedHistory", "historyEvent", b"historyEvent", "propagatedHistory", b"propagatedHistory"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_propagatedHistory", b"_propagatedHistory", "historyEvent", b"historyEvent", "propagatedHistory", b"propagatedHistory", "targetInstanceId", b"targetInstanceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__propagatedHistory: _TypeAlias = _typing.Literal["propagatedHistory"]  # noqa: Y015
    _WhichOneofArgType__propagatedHistory: _TypeAlias = _typing.Literal["_propagatedHistory", b"_propagatedHistory"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__propagatedHistory) -> _WhichOneofReturnType__propagatedHistory | None: ...

Global___WorkflowRuntimeStateMessage: _TypeAlias = WorkflowRuntimeStateMessage  # noqa: Y015
