# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'runtime_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dapr.ext.workflow._durabletask.internal import orchestration_pb2 as orchestration__pb2
from dapr.ext.workflow._durabletask.internal import history_events_pb2 as history__events__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13runtime_state.proto\x12\x1d\x64urabletask.protos.backend.v1\x1a\x13orchestration.proto\x1a\x14history_events.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"_\n\x13RuntimeStateStalled\x12\x1e\n\x06reason\x18\x01 \x01(\x0e\x32\x0e.StalledReason\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_description\"\xbc\x05\n\x14WorkflowRuntimeState\x12\x12\n\ninstanceId\x18\x01 \x01(\t\x12 \n\tnewEvents\x18\x02 \x03(\x0b\x32\r.HistoryEvent\x12 \n\toldEvents\x18\x03 \x03(\x0b\x32\r.HistoryEvent\x12#\n\x0cpendingTasks\x18\x04 \x03(\x0b\x32\r.HistoryEvent\x12$\n\rpendingTimers\x18\x05 \x03(\x0b\x32\r.HistoryEvent\x12S\n\x0fpendingMessages\x18\x06 \x03(\x0b\x32:.durabletask.protos.backend.v1.WorkflowRuntimeStateMessage\x12*\n\nstartEvent\x18\x07 \x01(\x0b\x32\x16.ExecutionStartedEvent\x12\x30\n\x0e\x63ompletedEvent\x18\x08 \x01(\x0b\x32\x18.ExecutionCompletedEvent\x12/\n\x0b\x63reatedTime\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0flastUpdatedTime\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rcompletedTime\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0e\x63ontinuedAsNew\x18\x0c \x01(\x08\x12\x13\n\x0bisSuspended\x18\r \x01(\x08\x12\x32\n\x0c\x63ustomStatus\x18\x0e \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12H\n\x07stalled\x18\x0f \x01(\x0b\x32\x32.durabletask.protos.backend.v1.RuntimeStateStalledH\x00\x88\x01\x01\x42\n\n\x08_stalled\"\xa6\x01\n\x1bWorkflowRuntimeStateMessage\x12#\n\x0chistoryEvent\x18\x01 \x01(\x0b\x32\r.HistoryEvent\x12\x18\n\x10targetInstanceId\x18\x02 \x01(\t\x12\x32\n\x11propagatedHistory\x18\x03 \x01(\x0b\x32\x12.PropagatedHistoryH\x00\x88\x01\x01\x42\x14\n\x12_propagatedHistoryBV\n+io.dapr.durabletask.implementation.protobufZ\x0b/api/protos\xaa\x02\x19\x44\x61pr.DurableTask.Protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dapr.ext.workflow._durabletask.internal.runtime_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+io.dapr.durabletask.implementation.protobufZ\013/api/protos\252\002\031Dapr.DurableTask.Protobuf'
  _globals['_RUNTIMESTATESTALLED']._serialized_start=162
  _globals['_RUNTIMESTATESTALLED']._serialized_end=257
  _globals['_WORKFLOWRUNTIMESTATE']._serialized_start=260
  _globals['_WORKFLOWRUNTIMESTATE']._serialized_end=960
  _globals['_WORKFLOWRUNTIMESTATEMESSAGE']._serialized_start=963
  _globals['_WORKFLOWRUNTIMESTATEMESSAGE']._serialized_end=1129
# @@protoc_insertion_point(module_scope)
