# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: invokecaller
  labels:
    app: invokecaller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invokecaller
  template:
    metadata:
      labels:
        app: invokecaller
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "invoke-caller"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
      - name: invokecaller
        image: invokegrpcproxy:latest  # EDIT HERE: Replace the image name
        command: ["python"]
        args: ["/app/invoke-caller.py"]
        imagePullPolicy: Always
