"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2021 The Dapr Authors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import any_pb2 as _any_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HTTPExtension(_message.Message):
    """HTTPExtension includes HTTP verb and querystring
    when Dapr runtime delivers HTTP content.

    For example, when callers calls http invoke api
    `POST http://localhost:3500/v1.0/invoke/<app_id>/method/<method>?query1=value1&query2=value2`

    Dapr runtime will parse POST as a verb and extract querystring to quersytring map.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Verb:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _VerbEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HTTPExtension._Verb.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NONE: HTTPExtension._Verb.ValueType  # 0
        GET: HTTPExtension._Verb.ValueType  # 1
        HEAD: HTTPExtension._Verb.ValueType  # 2
        POST: HTTPExtension._Verb.ValueType  # 3
        PUT: HTTPExtension._Verb.ValueType  # 4
        DELETE: HTTPExtension._Verb.ValueType  # 5
        CONNECT: HTTPExtension._Verb.ValueType  # 6
        OPTIONS: HTTPExtension._Verb.ValueType  # 7
        TRACE: HTTPExtension._Verb.ValueType  # 8
        PATCH: HTTPExtension._Verb.ValueType  # 9

    class Verb(_Verb, metaclass=_VerbEnumTypeWrapper):
        """Type of HTTP 1.1 Methods
        RFC 7231: https://tools.ietf.org/html/rfc7231#page-24
        RFC 5789: https://datatracker.ietf.org/doc/html/rfc5789
        """

    NONE: HTTPExtension.Verb.ValueType  # 0
    GET: HTTPExtension.Verb.ValueType  # 1
    HEAD: HTTPExtension.Verb.ValueType  # 2
    POST: HTTPExtension.Verb.ValueType  # 3
    PUT: HTTPExtension.Verb.ValueType  # 4
    DELETE: HTTPExtension.Verb.ValueType  # 5
    CONNECT: HTTPExtension.Verb.ValueType  # 6
    OPTIONS: HTTPExtension.Verb.ValueType  # 7
    TRACE: HTTPExtension.Verb.ValueType  # 8
    PATCH: HTTPExtension.Verb.ValueType  # 9

    VERB_FIELD_NUMBER: _builtins.int
    QUERYSTRING_FIELD_NUMBER: _builtins.int
    verb: Global___HTTPExtension.Verb.ValueType
    """Required. HTTP verb."""
    querystring: _builtins.str
    """Optional. querystring represents an encoded HTTP url query string in the following format: name=value&name2=value2"""
    def __init__(
        self,
        *,
        verb: Global___HTTPExtension.Verb.ValueType = ...,
        querystring: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["querystring", b"querystring", "verb", b"verb"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HTTPExtension: _TypeAlias = HTTPExtension  # noqa: Y015

@_typing.final
class InvokeRequest(_message.Message):
    """InvokeRequest is the message to invoke a method with the data.
    This message is used in InvokeService of Dapr gRPC Service and OnInvoke
    of AppCallback gRPC service.
    """

    DESCRIPTOR: _descriptor.Descriptor

    METHOD_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    HTTP_EXTENSION_FIELD_NUMBER: _builtins.int
    method: _builtins.str
    """Required. method is a method name which will be invoked by caller."""
    content_type: _builtins.str
    """The type of data content.

    This field is required if data delivers http request body
    Otherwise, this is optional.
    """
    @_builtins.property
    def data(self) -> _any_pb2.Any:
        """Required in unary RPCs. Bytes value or Protobuf message which caller sent.
        Dapr treats Any.value as bytes type if Any.type_url is unset.
        """

    @_builtins.property
    def http_extension(self) -> Global___HTTPExtension:
        """HTTP specific fields if request conveys http-compatible request.

        This field is required for http-compatible request. Otherwise,
        this field is optional.
        """

    def __init__(
        self,
        *,
        method: _builtins.str = ...,
        data: _any_pb2.Any | None = ...,
        content_type: _builtins.str = ...,
        http_extension: Global___HTTPExtension | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "http_extension", b"http_extension"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "data", b"data", "http_extension", b"http_extension", "method", b"method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InvokeRequest: _TypeAlias = InvokeRequest  # noqa: Y015

@_typing.final
class InvokeResponse(_message.Message):
    """InvokeResponse is the response message including data and its content type
    from app callback.
    This message is used in InvokeService of Dapr gRPC Service and OnInvoke
    of AppCallback gRPC service.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    content_type: _builtins.str
    """Required. The type of data content."""
    @_builtins.property
    def data(self) -> _any_pb2.Any:
        """Required in unary RPCs. The content body of InvokeService response."""

    def __init__(
        self,
        *,
        data: _any_pb2.Any | None = ...,
        content_type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InvokeResponse: _TypeAlias = InvokeResponse  # noqa: Y015

@_typing.final
class StreamPayload(_message.Message):
    """Chunk of data sent in a streaming request or response.
    This is used in requests including InternalInvokeRequestStream.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    SEQ_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    """Data sent in the chunk.
    The amount of data included in each chunk is up to the discretion of the sender, and can be empty.
    Additionally, the amount of data doesn't need to be fixed and subsequent messages can send more, or less, data.
    Receivers must not make assumptions about the number of bytes they'll receive in each chunk.
    """
    seq: _builtins.int
    """Sequence number. This is a counter that starts from 0 and increments by 1 on each chunk sent."""
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        seq: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "seq", b"seq"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamPayload: _TypeAlias = StreamPayload  # noqa: Y015

@_typing.final
class StateItem(_message.Message):
    """StateItem represents state key, value, and additional options to save state."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    ETAG_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    """Required. The state key"""
    value: _builtins.bytes
    """Required. The state data for key"""
    @_builtins.property
    def etag(self) -> Global___Etag:
        """The entity tag which represents the specific version of data.
        The exact ETag format is defined by the corresponding data store.
        """

    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """The metadata which will be passed to state store component."""

    @_builtins.property
    def options(self) -> Global___StateOptions:
        """Options for concurrency and consistency to save the state."""

    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
        etag: Global___Etag | None = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        options: Global___StateOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["etag", b"etag", "options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["etag", b"etag", "key", b"key", "metadata", b"metadata", "options", b"options", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StateItem: _TypeAlias = StateItem  # noqa: Y015

@_typing.final
class Etag(_message.Message):
    """Etag represents a state item version"""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    """value sets the etag value"""
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Etag: _TypeAlias = Etag  # noqa: Y015

@_typing.final
class StateOptions(_message.Message):
    """StateOptions configures concurrency and consistency for state operations"""

    DESCRIPTOR: _descriptor.Descriptor

    class _StateConcurrency:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateConcurrencyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StateOptions._StateConcurrency.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CONCURRENCY_UNSPECIFIED: StateOptions._StateConcurrency.ValueType  # 0
        CONCURRENCY_FIRST_WRITE: StateOptions._StateConcurrency.ValueType  # 1
        CONCURRENCY_LAST_WRITE: StateOptions._StateConcurrency.ValueType  # 2

    class StateConcurrency(_StateConcurrency, metaclass=_StateConcurrencyEnumTypeWrapper):
        """Enum describing the supported concurrency for state."""

    CONCURRENCY_UNSPECIFIED: StateOptions.StateConcurrency.ValueType  # 0
    CONCURRENCY_FIRST_WRITE: StateOptions.StateConcurrency.ValueType  # 1
    CONCURRENCY_LAST_WRITE: StateOptions.StateConcurrency.ValueType  # 2

    class _StateConsistency:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateConsistencyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StateOptions._StateConsistency.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CONSISTENCY_UNSPECIFIED: StateOptions._StateConsistency.ValueType  # 0
        CONSISTENCY_EVENTUAL: StateOptions._StateConsistency.ValueType  # 1
        CONSISTENCY_STRONG: StateOptions._StateConsistency.ValueType  # 2

    class StateConsistency(_StateConsistency, metaclass=_StateConsistencyEnumTypeWrapper):
        """Enum describing the supported consistency for state."""

    CONSISTENCY_UNSPECIFIED: StateOptions.StateConsistency.ValueType  # 0
    CONSISTENCY_EVENTUAL: StateOptions.StateConsistency.ValueType  # 1
    CONSISTENCY_STRONG: StateOptions.StateConsistency.ValueType  # 2

    CONCURRENCY_FIELD_NUMBER: _builtins.int
    CONSISTENCY_FIELD_NUMBER: _builtins.int
    concurrency: Global___StateOptions.StateConcurrency.ValueType
    consistency: Global___StateOptions.StateConsistency.ValueType
    def __init__(
        self,
        *,
        concurrency: Global___StateOptions.StateConcurrency.ValueType = ...,
        consistency: Global___StateOptions.StateConsistency.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["concurrency", b"concurrency", "consistency", b"consistency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StateOptions: _TypeAlias = StateOptions  # noqa: Y015

@_typing.final
class ConfigurationItem(_message.Message):
    """ConfigurationItem represents all the configuration with its name(key)."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VALUE_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    """Required. The value of configuration item."""
    version: _builtins.str
    """Version is response only and cannot be fetched. Store is not expected to keep all versions available"""
    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """the metadata which will be passed to/from configuration store component."""

    def __init__(
        self,
        *,
        value: _builtins.str = ...,
        version: _builtins.str = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata", "value", b"value", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConfigurationItem: _TypeAlias = ConfigurationItem  # noqa: Y015

@_typing.final
class JobFailurePolicy(_message.Message):
    """JobFailurePolicy defines the policy to apply when a job fails to trigger."""

    DESCRIPTOR: _descriptor.Descriptor

    DROP_FIELD_NUMBER: _builtins.int
    CONSTANT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def drop(self) -> Global___JobFailurePolicyDrop: ...
    @_builtins.property
    def constant(self) -> Global___JobFailurePolicyConstant: ...
    def __init__(
        self,
        *,
        drop: Global___JobFailurePolicyDrop | None = ...,
        constant: Global___JobFailurePolicyConstant | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["constant", b"constant", "drop", b"drop", "policy", b"policy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["constant", b"constant", "drop", b"drop", "policy", b"policy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_policy: _TypeAlias = _typing.Literal["drop", "constant"]  # noqa: Y015
    _WhichOneofArgType_policy: _TypeAlias = _typing.Literal["policy", b"policy"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_policy) -> _WhichOneofReturnType_policy | None: ...

Global___JobFailurePolicy: _TypeAlias = JobFailurePolicy  # noqa: Y015

@_typing.final
class JobFailurePolicyDrop(_message.Message):
    """JobFailurePolicyDrop is a policy which drops the job tick when the job fails to trigger."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___JobFailurePolicyDrop: _TypeAlias = JobFailurePolicyDrop  # noqa: Y015

@_typing.final
class JobFailurePolicyConstant(_message.Message):
    """JobFailurePolicyConstant is a policy which retries the job at a consistent interval when the job fails to trigger."""

    DESCRIPTOR: _descriptor.Descriptor

    INTERVAL_FIELD_NUMBER: _builtins.int
    MAX_RETRIES_FIELD_NUMBER: _builtins.int
    max_retries: _builtins.int
    """max_retries is the optional maximum number of retries to attempt before giving up.
    If unset, the Job will be retried indefinitely.
    """
    @_builtins.property
    def interval(self) -> _duration_pb2.Duration:
        """interval is the constant delay to wait before retrying the job."""

    def __init__(
        self,
        *,
        interval: _duration_pb2.Duration | None = ...,
        max_retries: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_max_retries", b"_max_retries", "interval", b"interval", "max_retries", b"max_retries"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_max_retries", b"_max_retries", "interval", b"interval", "max_retries", b"max_retries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__max_retries: _TypeAlias = _typing.Literal["max_retries"]  # noqa: Y015
    _WhichOneofArgType__max_retries: _TypeAlias = _typing.Literal["_max_retries", b"_max_retries"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_retries) -> _WhichOneofReturnType__max_retries | None: ...

Global___JobFailurePolicyConstant: _TypeAlias = JobFailurePolicyConstant  # noqa: Y015
