name: dapr-python

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - release-*
      - feature/*
  workflow_dispatch:
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync --frozen --all-packages --group dev
    - name: Run Autoformatter
      run: |
        uv run ruff check --fix && uv run ruff format
        statusResult=$(git status -u --porcelain)
        if [ -z "$statusResult" ]
        then
            exit 0
        else
            echo "Source files are not formatted correctly. Run 'uv run ruff check --fix && uv run ruff format'."
            exit 1
        fi

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_ver: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python_ver }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python_ver }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync --frozen --all-packages --group dev
    - name: Check Typing
      run: uv run mypy
    - name: Run unit-tests
      run: |
        uv run coverage run -m unittest discover -v ./tests
        for dir in ext/*/tests; do
            uv run coverage run -a -m unittest discover -v "./$dir"
        done
        uv run coverage run -a -m pytest -m "not e2e" ./ext/dapr-ext-workflow/tests/durabletask/
        uv run coverage xml
    - name: Upload test coverage
      uses: codecov/codecov-action@v6
